//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSql.EntityGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxConnectionString_Text {
            get {
                return ((string)(this["comboBoxConnectionString_Text"]));
            }
            set {
                this["comboBoxConnectionString_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsEntity01_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsEntity01_Checked"]));
            }
            set {
                this["checkBoxNameOptionsEntity01_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsEntity02_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsEntity02_Checked"]));
            }
            set {
                this["checkBoxNameOptionsEntity02_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsEntity03_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsEntity03_Checked"]));
            }
            set {
                this["checkBoxNameOptionsEntity03_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsEntity04_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsEntity04_Checked"]));
            }
            set {
                this["checkBoxNameOptionsEntity04_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsProperty02_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsProperty02_Checked"]));
            }
            set {
                this["checkBoxNameOptionsProperty02_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsProperty01_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsProperty01_Checked"]));
            }
            set {
                this["checkBoxNameOptionsProperty01_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsProperty03_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsProperty03_Checked"]));
            }
            set {
                this["checkBoxNameOptionsProperty03_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNameOptionsProperty04_Checked {
            get {
                return ((bool)(this["checkBoxNameOptionsProperty04_Checked"]));
            }
            set {
                this["checkBoxNameOptionsProperty04_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonTemplateStyle01_Checked {
            get {
                return ((bool)(this["radioButtonTemplateStyle01_Checked"]));
            }
            set {
                this["radioButtonTemplateStyle01_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonTemplateStyle02_Checked {
            get {
                return ((bool)(this["radioButtonTemplateStyle02_Checked"]));
            }
            set {
                this["radioButtonTemplateStyle02_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonTemplateStyle03_Checked {
            get {
                return ((bool)(this["radioButtonTemplateStyle03_Checked"]));
            }
            set {
                this["radioButtonTemplateStyle03_Checked"] = value;
            }
        }
    }
}
